name: Deno Deploy (classic)
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deno-classic-deploy-group
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/deployctl@v1
        with:
          project: httpecho
          entrypoint: main.ts
