name: sync-codesandbox
on:
  push:
    branches: [master]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: kou029w/sync-codesandbox@master
        with: { url: fe8lf.sse.codesandbox.io }
