name: sync-glitch
on:
  push:
    branches: [master]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git remote add glitch "${{ secrets.GLITCH_GIT_URL }}"
          git push glitch @
