name: sync-glitch
on:
  push:
    branches: [master]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: npx sync-glitch-cli
        env:
          GH_REPO: "${{ github.repository }}"
          GLITCH_PROJECT_ID: "${{ secrets.GLITCH_PROJECT_ID }}"
          GLITCH_TOKEN: "${{ secrets.GLITCH_TOKEN }}"
